# Generated by Django 4.1.5 on 2023-01-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MovieDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("director", models.CharField(max_length=200)),
                ("cast", models.CharField(max_length=200)),
                ("genre", models.CharField(max_length=200)),
                ("star", models.FloatField()),
                ("runtime", models.CharField(max_length=200)),
                ("review", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MovieReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("released", models.IntegerField()),
                ("genre", models.CharField(max_length=200)),
                ("star", models.FloatField()),
            ],
        ),
    ]
