# Generated by Django 4.1.5 on 2023-01-18 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IdeaLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("toolName", models.CharField(max_length=100)),
                ("toolCategory", models.CharField(max_length=100)),
                ("toolContent", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Ideas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ideaName", models.CharField(max_length=100)),
                ("ideaImg", models.ImageField(blank=True, upload_to="posts/%Y%m%d")),
                ("ideaContent", models.TextField()),
                ("ideaInterest", models.IntegerField()),
                (
                    "ideaLike",
                    models.ManyToManyField(
                        blank=True, related_name="likes", to="posts.idealike"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="idealike",
            name="idea",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.ideas",
            ),
        ),
    ]
